### ISSUE TITLE
Module 'vapoursynth' has no attribute 'get_core'

### ISSUE THREAD

**Issue by 150481878** [vcb-s/rp-checker#2]
I guess the error is about the VS API3 or API4 edtion?

**Comment by tautcony** [comment]
You should download the latest version from the release page, which has removed the use of get_core.

**Comment by xxhhlk** [comment]
v1.0.6.6 same error... Maybe fix not realeased?

**Comment by tautcony** [comment]
[v1.0.7.0](https://github.com/vcb-s/rp-checker/releases/tag/1.0.7.0) has been released.

**Comment by xxhhlk** [comment]
> [v1.0.7.0](https://github.com/vcb-s/rp-checker/releases/tag/1.0.7.0) has been released.

Hello, it works, but another error was reported when using the PSNR(VS) option:

> AttributeError: No attribute with the name complane exists. Did you mistype a plugin namespace?

Does this mean that a certain plugin is missing? But I searched and didn't find it. GMSD(VS) works fine.

Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)] on win32

VapourSynth Video Processing Library
Copyright (c) 2012-2022 Fredrik Mellbin
Core R61
API R4.0
API R3.6
Options: -

**Comment by tautcony** [comment]
Current script template requires both lsmas and [vs-ComparePlane](https://github.com/AmusementClub/vs-ComparePlane) plugins to be installed before using it.

**Comment by xxhhlk** [comment]
Works perfectly. Thanks.
